[build-system]
requires = ["hatchling>=1.26"]
build-backend = "hatchling.build"

[project]
name = "symjoy"
version = "2.6.0"

authors = [
    { name = "Vishwanath M M", email = "vishwanathmm2005@gmail.com" }
]

description = "A structured, metadata-driven Unicode symbol engine for Python."

readme = "README.md"
requires-python = ">=3.12"

license = { text = "MIT" }

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

keywords = [
    "unicode",
    "emoji",
    "symbols",
    "arrows",
    "math symbols",
    "currency",
    "unicode library"
]

[project.urls]
Homepage = "https://github.com/vishwanathdvgmm/symjoy"
Repository = "https://github.com/vishwanathdvgmm/symjoy"
Issues = "https://github.com/vishwanathdvgmm/symjoy/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/symjoy"]

[tool.hatch.build.targets.sdist]
include = [
    "src/symjoy",
    "README.md",
    "CHANGELOG.md",
    "MIGRATION.md",
    "ARCHITECTURE.md",
    "LICENSE"
]